/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "data_path.sv:1" *)
module data_path(clk, reset, enable, cont_mode, cds, erase, corr, expose, convert, read, idle, pixel_select);
  (* src = "data_path.sv:5" *)
  input cds;
  (* src = "data_path.sv:1" *)
  input clk;
  (* src = "data_path.sv:4" *)
  input cont_mode;
  (* src = "data_path.sv:9" *)
  output convert;
  (* src = "data_path.sv:7" *)
  output corr;
  (* src = "data_path.sv:24" *)
  wire [15:0] counter;
  (* src = "data_path.sv:3" *)
  input enable;
  (* src = "data_path.sv:6" *)
  output erase;
  (* src = "data_path.sv:8" *)
  output expose;
  (* src = "data_path.sv:11" *)
  output idle;
  (* src = "data_path.sv:23" *)
  wire [3:0] next_state;
  (* src = "data_path.sv:12" *)
  output [1:0] pixel_select;
  (* src = "data_path.sv:10" *)
  output read;
  (* src = "data_path.sv:2" *)
  input reset;
  (* src = "data_path.sv:22" *)
  wire [3:0] state;
  assign convert = 1'h0;
  assign corr = 1'h0;
  assign counter = 16'h0000;
  assign erase = 1'h0;
  assign expose = 1'h0;
  assign idle = 1'h1;
  assign next_state = 4'h0;
  assign pixel_select = 2'h0;
  assign read = 1'h0;
  assign state = 4'h0;
endmodule
