/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "sub.sv:1" *)
module sub(a, b, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  (* src = "sub.sv:2" *)
  wire _026_;
  (* src = "sub.sv:2" *)
  wire _027_;
  (* src = "sub.sv:2" *)
  wire _028_;
  (* src = "sub.sv:2" *)
  wire _029_;
  (* src = "sub.sv:2" *)
  wire _030_;
  (* src = "sub.sv:2" *)
  wire _031_;
  (* src = "sub.sv:2" *)
  wire _032_;
  (* src = "sub.sv:2" *)
  wire _033_;
  (* src = "sub.sv:3" *)
  wire _034_;
  (* src = "sub.sv:3" *)
  wire _035_;
  (* src = "sub.sv:3" *)
  wire _036_;
  (* src = "sub.sv:3" *)
  wire _037_;
  (* src = "sub.sv:3" *)
  wire _038_;
  (* src = "sub.sv:3" *)
  wire _039_;
  (* src = "sub.sv:3" *)
  wire _040_;
  (* src = "sub.sv:3" *)
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* src = "sub.sv:4" *)
  wire _076_;
  (* src = "sub.sv:4" *)
  wire _077_;
  (* src = "sub.sv:4" *)
  wire _078_;
  (* src = "sub.sv:4" *)
  wire _079_;
  (* src = "sub.sv:4" *)
  wire _080_;
  (* src = "sub.sv:4" *)
  wire _081_;
  (* src = "sub.sv:4" *)
  wire _082_;
  (* src = "sub.sv:4" *)
  wire _083_;
  (* src = "sub.sv:2" *)
  input [7:0] a;
  (* src = "sub.sv:3" *)
  input [7:0] b;
  (* src = "sub.sv:4" *)
  output [7:0] out;
  IVX1_CV _084_ (
    .A(_034_),
    .Y(_042_)
  );
  IVX1_CV _085_ (
    .A(_027_),
    .Y(_043_)
  );
  IVX1_CV _086_ (
    .A(_028_),
    .Y(_044_)
  );
  IVX1_CV _087_ (
    .A(_037_),
    .Y(_045_)
  );
  IVX1_CV _088_ (
    .A(_030_),
    .Y(_046_)
  );
  IVX1_CV _089_ (
    .A(_031_),
    .Y(_047_)
  );
  IVX1_CV _090_ (
    .A(_032_),
    .Y(_048_)
  );
  NDX1_CV _091_ (
    .A(_042_),
    .B(_026_),
    .Y(_049_)
  );
  EOX1_CV _092_ (
    .A(_034_),
    .B(_026_),
    .Y(_076_)
  );
  NDX1_CV _093_ (
    .A(_035_),
    .B(_043_),
    .Y(_050_)
  );
  ENX1_CV _094_ (
    .A(_035_),
    .B(_027_),
    .Y(_051_)
  );
  NDX1_CV _095_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  EOX1_CV _096_ (
    .A(_049_),
    .B(_051_),
    .Y(_077_)
  );
  NDX1_CV _097_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NDX1_CV _098_ (
    .A(_036_),
    .B(_044_),
    .Y(_054_)
  );
  ENX1_CV _099_ (
    .A(_036_),
    .B(_028_),
    .Y(_055_)
  );
  NDX1_CV _100_ (
    .A(_053_),
    .B(_055_),
    .Y(_056_)
  );
  EOX1_CV _101_ (
    .A(_053_),
    .B(_055_),
    .Y(_078_)
  );
  ANX1_CV _102_ (
    .A(_054_),
    .B(_056_),
    .Y(_057_)
  );
  NDX1_CV _103_ (
    .A(_045_),
    .B(_029_),
    .Y(_058_)
  );
  ORX1_CV _104_ (
    .A(_045_),
    .B(_029_),
    .Y(_059_)
  );
  ENX1_CV _105_ (
    .A(_037_),
    .B(_029_),
    .Y(_060_)
  );
  ENX1_CV _106_ (
    .A(_057_),
    .B(_060_),
    .Y(_079_)
  );
  NDX1_CV _107_ (
    .A(_038_),
    .B(_046_),
    .Y(_061_)
  );
  ENX1_CV _108_ (
    .A(_038_),
    .B(_030_),
    .Y(_062_)
  );
  NDX1_CV _109_ (
    .A(_057_),
    .B(_059_),
    .Y(_063_)
  );
  ANX1_CV _110_ (
    .A(_058_),
    .B(_063_),
    .Y(_064_)
  );
  NDX1_CV _111_ (
    .A(_062_),
    .B(_064_),
    .Y(_065_)
  );
  EOX1_CV _112_ (
    .A(_062_),
    .B(_064_),
    .Y(_080_)
  );
  NDX1_CV _113_ (
    .A(_061_),
    .B(_065_),
    .Y(_066_)
  );
  NDX1_CV _114_ (
    .A(_039_),
    .B(_047_),
    .Y(_067_)
  );
  ENX1_CV _115_ (
    .A(_039_),
    .B(_031_),
    .Y(_068_)
  );
  NDX1_CV _116_ (
    .A(_066_),
    .B(_068_),
    .Y(_069_)
  );
  EOX1_CV _117_ (
    .A(_066_),
    .B(_068_),
    .Y(_081_)
  );
  NDX1_CV _118_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NDX1_CV _119_ (
    .A(_040_),
    .B(_048_),
    .Y(_071_)
  );
  ENX1_CV _120_ (
    .A(_040_),
    .B(_032_),
    .Y(_072_)
  );
  NDX1_CV _121_ (
    .A(_070_),
    .B(_072_),
    .Y(_073_)
  );
  EOX1_CV _122_ (
    .A(_070_),
    .B(_072_),
    .Y(_082_)
  );
  ANX1_CV _123_ (
    .A(_071_),
    .B(_073_),
    .Y(_074_)
  );
  ENX1_CV _124_ (
    .A(_041_),
    .B(_033_),
    .Y(_075_)
  );
  ENX1_CV _125_ (
    .A(_074_),
    .B(_075_),
    .Y(_083_)
  );
  assign _034_ = b[0];
  assign _026_ = a[0];
  assign out[0] = _076_;
  assign _035_ = b[1];
  assign _027_ = a[1];
  assign out[1] = _077_;
  assign _036_ = b[2];
  assign _028_ = a[2];
  assign out[2] = _078_;
  assign _037_ = b[3];
  assign _029_ = a[3];
  assign out[3] = _079_;
  assign _038_ = b[4];
  assign _030_ = a[4];
  assign out[4] = _080_;
  assign _039_ = b[5];
  assign _031_ = a[5];
  assign out[5] = _081_;
  assign _040_ = b[6];
  assign _032_ = a[6];
  assign out[6] = _082_;
  assign _041_ = b[7];
  assign _033_ = a[7];
  assign out[7] = _083_;
endmodule
