/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "counter.sv:1" *)
module counter(clk, reset, out);
  (* src = "counter.sv:8" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "counter.sv:8" *)
  wire _09_;
  (* src = "counter.sv:8" *)
  wire _10_;
  (* src = "counter.sv:8" *)
  wire _11_;
  (* src = "counter.sv:8" *)
  wire _12_;
  (* src = "counter.sv:8" *)
  wire _13_;
  (* src = "counter.sv:8" *)
  wire _14_;
  (* src = "counter.sv:8" *)
  wire _15_;
  (* src = "counter.sv:6" *)
  wire _16_;
  (* src = "counter.sv:6" *)
  wire _17_;
  (* src = "counter.sv:6" *)
  wire _18_;
  (* src = "counter.sv:6" *)
  wire _19_;
  (* src = "counter.sv:6" *)
  wire _20_;
  (* src = "counter.sv:6" *)
  wire _21_;
  (* src = "counter.sv:6" *)
  wire _22_;
  (* src = "counter.sv:6" *)
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "counter.sv:1" *)
  input clk;
  (* init = 8'h00 *)
  (* src = "counter.sv:6" *)
  wire [7:0] count;
  (* src = "counter.sv:3" *)
  output [7:0] out;
  (* src = "counter.sv:2" *)
  input reset;
  ANX1_CV _39_ (
    .A(_16_),
    .B(_17_),
    .Y(_24_)
  );
  ANX1_CV _40_ (
    .A(_18_),
    .B(_24_),
    .Y(_25_)
  );
  ANX1_CV _41_ (
    .A(_19_),
    .B(_25_),
    .Y(_26_)
  );
  EOX1_CV _42_ (
    .A(_19_),
    .B(_25_),
    .Y(_11_)
  );
  ANX1_CV _43_ (
    .A(_20_),
    .B(_26_),
    .Y(_27_)
  );
  EOX1_CV _44_ (
    .A(_20_),
    .B(_26_),
    .Y(_12_)
  );
  ANX1_CV _45_ (
    .A(_21_),
    .B(_27_),
    .Y(_28_)
  );
  EOX1_CV _46_ (
    .A(_21_),
    .B(_27_),
    .Y(_13_)
  );
  NDX1_CV _47_ (
    .A(_22_),
    .B(_28_),
    .Y(_29_)
  );
  EOX1_CV _48_ (
    .A(_22_),
    .B(_28_),
    .Y(_14_)
  );
  ENX1_CV _49_ (
    .A(_23_),
    .B(_29_),
    .Y(_15_)
  );
  EOX1_CV _50_ (
    .A(_16_),
    .B(_17_),
    .Y(_09_)
  );
  EOX1_CV _51_ (
    .A(_18_),
    .B(_24_),
    .Y(_10_)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _52_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .QN(_30_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _53_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .QN(_31_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _54_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(count[2]),
    .QN(_32_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _55_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(count[3]),
    .QN(_33_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _56_ (
    .CK(clk),
    .D(_00_[4]),
    .Q(count[4]),
    .QN(_34_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _57_ (
    .CK(clk),
    .D(_00_[5]),
    .Q(count[5]),
    .QN(_35_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _58_ (
    .CK(clk),
    .D(_00_[6]),
    .Q(count[6]),
    .QN(_36_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.sv:8" *)
  DFSRQNX1_CV _59_ (
    .CK(clk),
    .D(_00_[7]),
    .Q(count[7]),
    .QN(_37_),
    .R(reset),
    .S(1'h0)
  );
  assign out = count;
  assign _00_[0] = _30_;
  assign _18_ = count[2];
  assign _19_ = count[3];
  assign _00_[3] = _11_;
  assign _20_ = count[4];
  assign _00_[4] = _12_;
  assign _21_ = count[5];
  assign _00_[5] = _13_;
  assign _22_ = count[6];
  assign _00_[6] = _14_;
  assign _23_ = count[7];
  assign _00_[7] = _15_;
  assign _16_ = count[0];
  assign _17_ = count[1];
  assign _00_[1] = _09_;
  assign _00_[2] = _10_;
endmodule
