/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "pixel_top.sv:1" *)
module pixel_top(clk, reset);
  (* src = "pixel_top.sv:1" *)
  input clk;
  (* src = "pixel_top.sv:2" *)
  input reset;
endmodule
